import { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { Eye, EyeOff, ArrowRight } from 'lucide-react'
import Brand from '../components/Brand'
import { readJSON, writeJSON } from '../lib/storage'

export default function Login(){
 const [show,setShow]=useState(false),[error,setError]=useState(''),[loading,setLoading]=useState(false)
 const nav=useNavigate()
 const submit=e=>{e.preventDefault();setError('');const f=new FormData(e.currentTarget);const email=f.get('email'),password=f.get('password');if(!email||!password)return setError('Enter email and password.');const users=readJSON('tomatoUsers',[]);const found=users.find(u=>u.email.toLowerCase()===email.toLowerCase()&&u.password===password);if(!found)return setError('Account not found or password is incorrect. Register first if you are a new user.');setLoading(true);setTimeout(()=>{writeJSON('tomatoUser',{name:found.name,email:found.email});nav('/dashboard')},500)}
 return <AuthShell title="Welcome back" subtitle="Sign in to your tomato farm workspace."><form onSubmit={submit} className="space-y-4"><Field label="Email"><input name="email" type="email" className="input" placeholder="farmer@example.com"/></Field><Field label="Password"><div className="relative"><input name="password" type={show?'text':'password'} className="input pr-12" placeholder="Password"/><button type="button" className="absolute right-4 top-3.5" onClick={()=>setShow(!show)}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></Field>{error&&<p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button disabled={loading} className="flex w-full items-center justify-center gap-2 rounded-xl bg-red-700 py-3 font-black text-white">{loading?'Signing in...':<>Sign in <ArrowRight size={18}/></>}</button></form><p className="mt-6 text-center text-sm">New user? <Link to="/signup" className="font-black text-red-700">Register here</Link></p></AuthShell>
}
export function AuthShell({title,subtitle,children}){return <div className="grid min-h-screen lg:grid-cols-2"><div className="auth-tomato hidden p-10 text-white lg:flex lg:flex-col lg:justify-between"><Brand light/><div><p className="text-xs font-black uppercase tracking-[.2em] text-red-300">Tomato-only platform</p><h2 className="mt-4 max-w-xl text-5xl font-black">One workspace built around the tomato crop.</h2><p className="mt-4 max-w-lg leading-7 text-red-50">Leaf health, soil interpretation, weather and daily field tasks in one place.</p></div><p className="text-sm text-red-100">TomatoGuard AI Decision Support System</p></div><div className="flex items-center justify-center bg-[#faf9f5] p-6"><div className="w-full max-w-md"><div className="mb-8 lg:hidden"><Brand/></div><h1 className="text-4xl font-black">{title}</h1><p className="mt-2 text-stone-500">{subtitle}</p><div className="mt-8 rounded-3xl bg-white p-7 shadow-xl">{children}</div><Link to="/" className="mt-6 block text-center text-sm font-bold text-red-700">← Back to landing page</Link></div></div></div>}
function Field({label,children}){return <label className="block"><span className="mb-2 block text-sm font-bold">{label}</span>{children}</label>}
