import { Download, FileBarChart, Leaf, FlaskConical, CloudSun } from 'lucide-react'
import Page from '../components/Page'
import { readJSON } from '../lib/storage'
export default function Reports(){
 const soil=readJSON('tomatoSoilReport',null), disease=readJSON('tomatoDiseaseResult',null), weather=readJSON('tomatoWeatherResult',null)
 const download=()=>{const content=`TomatoGuard - Farm Report\nGenerated: ${new Date().toLocaleString()}\n\nDisease:\n${disease?JSON.stringify(disease,null,2):'No analysis available'}\n\nSoil:\n${soil?JSON.stringify(soil,null,2):'No analysis available'}\n\nWeather:\n${weather?JSON.stringify(weather,null,2):'No weather data available'}\n`;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type:'text/plain'}));a.download='tomato-farm-report.txt';a.click();URL.revokeObjectURL(a.href)}
 return <Page title="Reports" sub="This page only summarizes results that actually exist in the application." action={<button onClick={download} className="flex items-center gap-2 rounded-xl bg-red-700 px-5 py-3 font-black text-white"><Download size={18}/>Download report</button>}><div className="grid gap-5 md:grid-cols-3"><Box icon={Leaf} t="Disease result" v={disease?'Available':'Pending'} d={disease?.label||'No model result yet'}/><Box icon={FlaskConical} t="Soil report" v={soil?'Available':'Pending'} d={soil?.analysis?'Backend result received':'No backend result yet'}/><Box icon={CloudSun} t="Weather" v={weather?'Available':'Pending'} d={weather?.location||'No API response yet'}/></div><div className="card mt-5 p-6"><FileBarChart className="text-red-700"/><h2 className="mt-4 text-2xl font-black">Result history</h2><p className="mt-2 text-stone-500">As your backend stores timestamped analyses, this section can display real historical reports instead of placeholders.</p></div></Page>
}
function Box({icon:I,t,v,d}){return <div className="card p-6"><I className="text-red-700"/><p className="mt-4 text-sm text-stone-500">{t}</p><p className="mt-1 text-3xl font-black">{v}</p><p className="mt-2 text-xs text-stone-500">{d}</p></div>}
