import { useEffect, useState } from 'react'
import { Moon, Sun, Bell, Save } from 'lucide-react'
import Page from '../components/Page'
import { readJSON, writeJSON } from '../lib/storage'
export default function Settings(){
 const [theme,setTheme]=useState(localStorage.getItem('tomatoTheme')||'light')
 const [prefs,setPrefs]=useState(()=>readJSON('tomatoPrefs',{weather:true,disease:true,tasks:true,language:'English'})),[saved,setSaved]=useState(false)
 useEffect(()=>{localStorage.setItem('tomatoTheme',theme);document.documentElement.classList.toggle('dark',theme==='dark')},[theme])
 const save=()=>{writeJSON('tomatoPrefs',prefs);setSaved(true);setTimeout(()=>setSaved(false),1600)}
 return <Page title="Settings" sub="Control theme and notification preferences for the tomato decision-support workspace."><div className="grid gap-5 lg:grid-cols-2"><div className="card p-6"><p className="text-xs font-black uppercase tracking-[.16em] text-red-700">Appearance</p><h2 className="mt-1 text-xl font-black">Theme</h2><div className="mt-5 grid grid-cols-2 gap-3"><button onClick={()=>setTheme('light')} className={`rounded-2xl border p-5 text-left ${theme==='light'?'border-red-500 bg-red-50 dark:bg-red-950/20':'border-stone-200 dark:border-stone-700'}`}><Sun/><p className="mt-3 font-black">Light</p></button><button onClick={()=>setTheme('dark')} className={`rounded-2xl border p-5 text-left ${theme==='dark'?'border-red-500 bg-red-50 dark:bg-red-950/20':'border-stone-200 dark:border-stone-700'}`}><Moon/><p className="mt-3 font-black">Dark</p></button></div></div><div className="card p-6"><div className="flex gap-3"><Bell className="text-red-700"/><div><p className="text-xs font-black uppercase tracking-[.16em] text-red-700">Notifications</p><h2 className="mt-1 text-xl font-black">Alert preferences</h2></div></div><div className="mt-5 space-y-4">{[['weather','Weather alerts'],['disease','Disease-analysis alerts'],['tasks','Daily task reminders']].map(([k,l])=><label key={k} className="flex items-center justify-between rounded-xl bg-stone-50 p-4 dark:bg-stone-800"><span className="font-bold">{l}</span><input type="checkbox" checked={prefs[k]} onChange={e=>setPrefs({...prefs,[k]:e.target.checked})}/></label>)}<label><span className="mb-2 block text-sm font-bold">Language preference</span><select className="input" value={prefs.language} onChange={e=>setPrefs({...prefs,language:e.target.value})}><option>English</option><option>Hindi</option><option>Marathi</option></select></label><button onClick={save} className="flex w-full items-center justify-center gap-2 rounded-xl bg-red-700 py-3 font-black text-white"><Save size={18}/>Save settings</button>{saved&&<p className="text-center text-sm font-bold text-green-700">Settings saved.</p>}</div></div></div></Page>
}
