import { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { Eye, EyeOff, ArrowRight } from 'lucide-react'
import { AuthShell } from './Login'
import { readJSON, writeJSON } from '../lib/storage'

export default function Signup(){
 const [show,setShow]=useState(false),[error,setError]=useState(''),[loading,setLoading]=useState(false);const nav=useNavigate()
 const submit=e=>{e.preventDefault();setError('');const f=new FormData(e.currentTarget);const name=f.get('name'),email=f.get('email'),p=f.get('password'),c=f.get('confirm');if(!name||!email||!p||!c)return setError('Complete all required fields.');if(p.length<6)return setError('Password must be at least 6 characters.');if(p!==c)return setError('Passwords do not match.');if(!f.get('terms'))return setError('Accept the terms to continue.');const users=readJSON('tomatoUsers',[]);if(users.some(u=>u.email.toLowerCase()===email.toLowerCase()))return setError('An account with this email already exists. Please sign in.');const newUser={name,email,password:p};writeJSON('tomatoUsers',[...users,newUser]);writeJSON('tomatoUser',{name,email});writeJSON('tomatoProfile',{name,email,farm:'My Tomato Farm',location:'',variety:'Tomato',photo:''});setLoading(true);setTimeout(()=>nav('/dashboard'),500)}
 return <AuthShell title="Register farmer account" subtitle="New users create an account before entering the dashboard."><form onSubmit={submit} className="space-y-4"><label className="block"><span className="mb-2 block text-sm font-bold">Full name</span><input name="name" className="input" placeholder="Farmer name"/></label><label className="block"><span className="mb-2 block text-sm font-bold">Email</span><input name="email" type="email" className="input" placeholder="farmer@example.com"/></label><label className="block"><span className="mb-2 block text-sm font-bold">Password</span><div className="relative"><input name="password" type={show?'text':'password'} className="input pr-12" placeholder="Minimum 6 characters"/><button type="button" className="absolute right-4 top-3.5" onClick={()=>setShow(!show)}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></label><label className="block"><span className="mb-2 block text-sm font-bold">Confirm password</span><input name="confirm" type={show?'text':'password'} className="input"/></label><label className="flex items-start gap-2 text-sm text-stone-500"><input name="terms" type="checkbox" className="mt-1"/> I agree to the project platform terms and privacy notice.</label>{error&&<p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button disabled={loading} className="flex w-full items-center justify-center gap-2 rounded-xl bg-red-700 py-3 font-black text-white">{loading?'Creating account...':<>Create account <ArrowRight size={18}/></>}</button></form><p className="mt-6 text-center text-sm">Already registered? <Link to="/login" className="font-black text-red-700">Sign in</Link></p></AuthShell>
}
